# Generated by Django 6.0.3 on 2026-03-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moradores.morador')),
            ],
        ),
    ]
